Open-EO/openeo-processes

filter_bbox.json
tests/openapi.test.js
warp_projection.json

I'm not sure which of the existing categories is suitable, I tentatively added a category 'spatial'.
Closes #22

Added process: warp_projection

---

CHANGELOG.md
ndvi.json
normalized_difference.json

Solves #60 and makes ndvi more universally usable.

New definition for `ndvi` and `normalized_difference`

---

CHANGELOG.md
resample_cube_spatial.json
resample_cube_temporal.json
resample_spatial.json
tests/processes.test.js

Clarify resample_* descriptions

---

.travis.yml
CHANGELOG.md
arccos.json
arcsin.json
arctan.json
array_contains.json
array_find.json
arsinh.json
artanh.json
e.json
examples/array_contains_null.json
examples/array_find_null.json
examples/rename-enumerated-labels.json
ln.json
pi.json
rename_labels.json

Changes:
- Adapted to changes from https://github.com/Open-EO/openeo-api/issues/285 (need to be merged first!)
- Removed some examples I think are not so meaningful
- Added examples folder to help with issue #136
After merging this, I need to establish [redirects](https://stackoverflow.com/questions/31881810/redirect-to-url-including-an-anchor) from processes.openeo.org/ to the latest version folder.

Link to examples (and remove some not so helpful examples)

---

aggregate_temporal_period.json
anomaly.json
climatological_normal.json
tests/.words

Added dekad and decade(-ad) as discussed in issue #150.

#150: Added dekad and decades

---

CHANGELOG.md
apply_kernel.json

#170: apply_kernel - border parameter and nodata handling

---

load_uploaded_files.json
save_result.json

see #179 
depends on #177 / #178 , so merge/reject that one first

use "format parameters" in save_result/load_uploaded_files docs

---

CHANGELOG.md
merge_cubes.json

Clarified overlap resolver as discussed in #184

Clarify overlap resolver #184

---

CHANGELOG.md
is_infinite.json
is_nan.json
is_nodata.json
is_valid.json
nan.json

Fixes issue #189 and adds new processes. Let me know what you think.

Fix issue 189

---

CHANGELOG.md
meta/implementation.md

Describe that back-ends are recommended to implement optimizations (branching / short-cicruit) for `if` and conditions in general, see issue #246 for some details.

branching behavior and short circuit conditions #246

---

CHANGELOG.md
array_find.json
proposals/array_find_label.json

Reverse array_find

---

save_result.json

see https://github.com/Open-EO/openeo-api/pull/439

Update broken links to file format GDAL codes

---

CHANGELOG.md
aggregate_spatial.json
proposals/flatten_dimensions.json
proposals/unflatten_dimension.json

Clarify (un)flatten_dimension(s)

---

proposals/fit_class_random_forest.json
proposals/fit_regr_random_forest.json

Fixes #350, #339, #354, #355 - for context please see the corresponding issues.

Fixes for the random forest processes

---

CHANGELOG.md
load_collection.json
save_result.json

As discussed in the dev telco:
- Added a more concrete `DataCubeEmpty` exception to `save_result`.
- Added a `NoDataAvailable` exception to `load_collection`.

Added exceptions for empty data cube handling

---

CHANGELOG.md
proposals/array_modify.json

`array_modify`: Change the default value for `length` from `1` to `0`.

---

CHANGELOG.md
array_contains.json
eq.json
gt.json
gte.json
lt.json
lte.json
neq.json

Removed support for arrays and objects from comparisons. #208

---

proposals/aggregate_spatial_window.json

addresses minor typo in aggregate_spatial_window (and eliminate triple "to" sentence)

aggregate_spatial_window typo fix

---

proposals/i.json

This should be the good one @m-mohr. Sorry for the chaos with the previous PRs, I did a mess.

Adding imaginary unit

---

proposals/ard_surface_reflectance.json
proposals/atmospheric_correction.json
proposals/cloud_detection.json

stumbled on these while exploring the usage of enums in the specs
not sure if this deserves a changelog entry

Simplify some enum types

---

CHANGELOG.md
mask.json

`mask`: Add missing exception `IncompatibleDataCubes` #538

---

CHANGELOG.md
proposals/date_difference.json

date_difference: Add week as unit #506
