Open-EO/openeo-processes

ndvi.json

Maybe I'm missing something, but it seems more logical to call the output "ndvi"  instead of "normalized_difference"

ndvi process: default to output band name "ndvi"

---

CHANGELOG.md
aggregate_polygon.json

Two changes for `aggregate_polygon` (applies similarly to #107 if accepted):
- Doesn't allow returning a GeoJSON any longer. We can't really work with the returned GeoJSON anyway. To export GeoJSON use save_result on a vector data cube.
- This is the change to debate, based on issue #101: The data cube implicitly gets restricted to the bounds of the polygons as if `filter_polygon` would have been used afterwards.

aggregate_polygon improvements

---

CHANGELOG.md
array_contains.json
array_find.json
between.json
eq.json
gt.json
gte.json
lt.json
lte.json
neq.json
text_begins.json
text_contains.json
text_ends.json

Changes:
- Comparison processes `eq`, `gt`, `gte`, `lt`, `lte`, `neq` and `between` accept all data types as input for the operands.
- `text_begins`, `text_contains`, `text_ends`: `null` values are supported and get passed through.
- Fix: `between` may return a `null` value.
- Several clarifications
I think all changes are quite straightforward. The thing to debate is probably whether arrays and objects should be comparable or always return false?
Main reason for the changes was the absence of some data types from some of the comparison, especially booleans.

Improvements for comparison processes

---

CHANGELOG.md
add_dimension.json
aggregate_temporal.json
filter_bbox.json
filter_labels.json
labels.json
load_collection.json
rename_dimension.json
rename_labels.json
resample_spatial.json
tests/processes.test.js

Changes:
1. Remove support for PROJJSON as CRS. Now that we use CRS as dimension, it would complicate the label handling due to PROJJSON not being a number or string.
2. Don't explicitly specify the subtypes if a general type has been specified. For example, temporal strings are always allowed if strings are allowed thus it's not required to mention them explicitly in schemas. Clients should allow all subtypes for the general types to be passed.
3. Make sure labels are always strings or numbers.
Related PR in API: https://github.com/Open-EO/openeo-api/pull/254
Related commit in openeo.org: https://github.com/Open-EO/openeo.org/commit/bf9e8271c5df11a5ea46d5e3c6300df7dd9ad8e2

Cleaning up after recent changes

---

CHANGELOG.md
all.json
any.json

`any` and `all`: Renamed parameter `values` to `data`

---

CHANGELOG.md
constant.json

While working on support of user-defined processes it felt  that a `constant` process could be handy to avoid too much hardcoding of predefined values. With the `constant` process, you introduce a constant value node in the process graph, that you can reuse with `from_node`, instead of having to copy-paste that value all over the place. For standard openEO usage that is probably not necessary as the client probably hides that away, but for handcrafted user-defined processes it might be valuable.
Basic usage example:
```
"margin1": {
"process_id": "constant",
"arguments": {
"x": 0.1
}
},
"west1": {
"process_id": "subtract",
"arguments": {
"x": 3.5,
"y": {
"from_node": "margin"
}
}
},
"east1": {
"process_id": "add",
"arguments": {
"x": 3.8,
"y": {
"from_node": "margin"
}
}
}
```

Add `constant` process

---

CHANGELOG.md
mean.json

Two changes I'd like to get some reviews for:
1. Add a process graph as "alias" #137 - did I miss anything?
Especially wondering about whether sum and divide are actually called/executed for an an empty array as this would lead to a DivisionByZero exception although it strictly shouldn't throw.
2. Clarify how arrays with only null values are handled. That came up when implementing the alias. Does this work for all?

`mean`: add process graph, clarify null arrays

---

arcosh.json

The `process_graph` example, which is not valid anymore (Open-EO/openeo-api#285), broke (D28) validation of our backend because use the process specs directly through a git submodule

Remove `process_graph` example from arcosh (also see #151)

---

CHANGELOG.md
filter_temporal.json

Clarify contradicting statements in filter_temporal for the default value of the dimension parameter. By default all temporal dimensions are affected by the process. Fixes #203

Clarify contradicting statements in filter_temporal

---

proposals/ard_normalized_radar_backscatter.json

Don't require contributing area by default as most tools don't support it and also CEOS is likely to remove it from the spec.
Closes #223

CARD4L: Don't require contributing area by default #223

---

CHANGELOG.md
meta/subtype-schemas.json
proposals/load_uploaded_files.json
proposals/run_udf_externally.json
run_udf.json

Add regex patterns to subtypes to make them easier to distinguish if used for the same parameter (see run_udf).
* The file-path is aligned with the API, see https://github.com/Open-EO/openeo-api/pull/385
* The uri is now clearly an absolute URL in UDF processes (was already the case in run_udf) and we can enforce specific protocols in the schemas. Back-ends can extend that, e.g. by adding s3 or gcs.
* The udf-code is likely controversial, but I couldn't come up with good examples of a single line UDF and the subtype-schema already said it should be multi-line.
The idea came up when discussing #220.

Make it easier to distinguish strings (paths/urls/code/...)

---

proposals/ard_normalized_radar_backscatter.json
proposals/sar_backscatter.json

Specify that the resampling method in SAR backscatter processes is required to be bilinear, see #249 for details.

Specify resampling method in sar backscatter processes to be bilinear

---

CHANGELOG.md
meta/implementation.md
proposals/date_shfit.json
proposals/date_shift.json

Adds a new process date_shift, see #247.
Took the simplest path for now...

Manipulation of date & time

---

CHANGELOG.md
mask_polygon.json

This is a proposal to support multi polygons instead of just polygons in `mask_polygon`. See #237 for context.
It's not clear yet which target version this is for as it's not clear whether this is a breaking change.

mask_polygon: Support multi polygons #237

---

CHANGELOG.md
aggregate_temporal.json
aggregate_temporal_period.json

Fixes #263 
Could potentially be part of 1.1.0.

aggregate_temporal(_period): handling of empty intervals

---

CHANGELOG.md
proposals/array_create_labels.json

This fills a gap in the processes as we can't transmit labeled arrays easily via JSON. So this makes it possible for users to actually construct those and make use of processes that require labeled arrays to be passed.
The idea came up when writing up the `fit_curve` process in PR #240.

Add array_create_labels process

---

CHANGELOG.md
save_result.json

Clarify save_result

---

CHANGELOG.md
meta/implementation.md
quantiles.json

Fixes #296 
From what I read in #296, it seems only VITO would need to switch from "Legacy" to R_7 in their library and Sinergise would need to switch from "higher" to "linear". All other implementations seem to implement type 7 already.
I've not chosen to go for a list yet and only clarify the type for now. If there's demand for more types, we can add that later.

Quantiles: Clarify to use type 7

---

CHANGELOG.md
proposals/array_append.json
proposals/array_concat.json
proposals/array_modify.json

Added better support for labeled arrays in experimental array processes that previously simply discarded the labels. Affected processes:
- `array_append`
- `array_concat`
- `array_modify`
The idea is that this will help overall to improve support for labeled arrays and get a better solution for #233, e.g. through a modified version of `apply_dimension` (as discussed with @clausmichele).

Improve support for labeled arrays in experimental array processes

---

CHANGELOG.md
round.json

Tries to fix #326. I found it relatively hard to describe the behavior in "simple" English, it may need further fine-tuning. Thoughts?

`round`: Clarify that the rounding for ties applies not only for integers. #326

---

CHANGELOG.md
apply_neighborhood.json

We had a weird and uncommon behavior in apply_neighborhood, where you actually had to remove a parameter/property (instead of setting it to null or having null as the default value) to specify a specific behavior for the units. This PR is fixing this in a backward-compatible way by allowing null and setting the default value to null.

`apply_neighborhood`: Allow `null` as default value for units.

---

rename_labels.json

Fine-tune rename_labels #335

---

proposals/vector_to_random_points.json
proposals/vector_to_regular_points.json

Clarifications for vector_to_*_points

---

CHANGELOG.md
filter_bbox.json
load_collection.json
meta/subtype-schemas.json
proposals/load_result.json
resample_spatial.json

PROJ strings: They were deprecated in 1.x and now get removed in 2.0

Deprecated PROJ definitions for the CRS are not supported any longer.

---

CHANGELOG.md
between.json
eq.json
gt.json
gte.json
lt.json
lte.json
neq.json
proposals/date_difference.json
proposals/date_shift.json

This is a proposal to simplify the comparison processes. The discussions in #394 lead me to the conclusion that we may not want to handle date/times in so many processes specifically so that issues can be solved in some central places rather than spreading them into so many processes. Also, the old implementation was a bit suboptimal in that you had to parse the inputs first to detect whether the values are temporal values, potentially making the comparisons slower than needed. Most use-cases can likely be solved with a new process such as `date_difference.`.
This includes a breaking change for the comparison processes. The impact is assumed to be low as most date/time values would usually come from labels in timeseries, but label support seems very limited in back-ends right now. For …

Simplify comparison processes (and add date_difference)

---

order.json
rearrange.json

spin-off from #409   :stuck_out_tongue:

Improve summary of order process

---

CHANGELOG.md
proposals/load_http.json
proposals/load_url.json

Add load_url

---

CHANGELOG.md
sqrt.json

`sqrt`: Clarified that NaN is returned for negative numbers #474

---

CHANGELOG.md
clip.json

Had to remove the process_graph, which would not throw the error.
Fixes #472

`clip`: Throw an exception if min > max #472

---

CHANGELOG.md
array_append.json

`array_append`: Added `number` type for labels to be consistent with other processes. Default to numerical index instead of string.

`array_append`: Add number type for labels

---

CHANGELOG.md
proposals/apply_polygon.json

`apply_polygon`: rename `polygons` parameter to `geometries` (#511)

---

README.md

Fixes https://github.com/Open-EO/openeo-processes/issues/513

Remove mention to examples folder

---

CHANGELOG.md
proposals/apply_polygon.json

apply_polygon: datacube instead of raster-cube #524

---

CHANGELOG.md
proposals/run_udf_externally.json
run_udf.json

`run_udf`: Simplified and clarified the schema for `data` #515

---

CHANGELOG.md
dev/.words
proposals/load_stac.json

`load_stac`: Clarify handling of the `properties` parameter in the context of STAC APIs and static catalogs.
Closes #536

`load_stac`: Clarify the `properties` parameter
